# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/processMining.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/processMining.proto\x12\x07\x65xample\"\x1b\n\x07xesData\x12\x10\n\x08\x65ventlog\x18\x01 \x01(\t\"\x1e\n\njsonSchema\x12\x10\n\x08petrinet\x18\x01 \x01(\t2K\n\rProcessMining\x12:\n\x0fGetProcessModel\x12\x10.example.xesData\x1a\x13.example.jsonSchema\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.processMining_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_XESDATA']._serialized_start=38
  _globals['_XESDATA']._serialized_end=65
  _globals['_JSONSCHEMA']._serialized_start=67
  _globals['_JSONSCHEMA']._serialized_end=97
  _globals['_PROCESSMINING']._serialized_start=99
  _globals['_PROCESSMINING']._serialized_end=174
# @@protoc_insertion_point(module_scope)
