// source: temporalAnalysis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.TemporalAnalysis.JsonEventlog');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.TemporalAnalysis.EventLog');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TemporalAnalysis.JsonEventlog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TemporalAnalysis.JsonEventlog.repeatedFields_, null);
};
goog.inherits(proto.TemporalAnalysis.JsonEventlog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TemporalAnalysis.JsonEventlog.displayName = 'proto.TemporalAnalysis.JsonEventlog';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TemporalAnalysis.JsonEventlog.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TemporalAnalysis.JsonEventlog.prototype.toObject = function(opt_includeInstance) {
  return proto.TemporalAnalysis.JsonEventlog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TemporalAnalysis.JsonEventlog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TemporalAnalysis.JsonEventlog.toObject = function(includeInstance, msg) {
  var f, obj = {
    companyid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    eventlogsList: jspb.Message.toObjectList(msg.getEventlogsList(),
    proto.TemporalAnalysis.EventLog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TemporalAnalysis.JsonEventlog}
 */
proto.TemporalAnalysis.JsonEventlog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TemporalAnalysis.JsonEventlog;
  return proto.TemporalAnalysis.JsonEventlog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TemporalAnalysis.JsonEventlog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TemporalAnalysis.JsonEventlog}
 */
proto.TemporalAnalysis.JsonEventlog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCompanyid(value);
      break;
    case 2:
      var value = new proto.TemporalAnalysis.EventLog;
      reader.readMessage(value,proto.TemporalAnalysis.EventLog.deserializeBinaryFromReader);
      msg.addEventlogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TemporalAnalysis.JsonEventlog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TemporalAnalysis.JsonEventlog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TemporalAnalysis.JsonEventlog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TemporalAnalysis.JsonEventlog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCompanyid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getEventlogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.TemporalAnalysis.EventLog.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 CompanyId = 1;
 * @return {number}
 */
proto.TemporalAnalysis.JsonEventlog.prototype.getCompanyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.TemporalAnalysis.JsonEventlog} returns this
 */
proto.TemporalAnalysis.JsonEventlog.prototype.setCompanyid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated EventLog eventlogs = 2;
 * @return {!Array<!proto.TemporalAnalysis.EventLog>}
 */
proto.TemporalAnalysis.JsonEventlog.prototype.getEventlogsList = function() {
  return /** @type{!Array<!proto.TemporalAnalysis.EventLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TemporalAnalysis.EventLog, 2));
};


/**
 * @param {!Array<!proto.TemporalAnalysis.EventLog>} value
 * @return {!proto.TemporalAnalysis.JsonEventlog} returns this
*/
proto.TemporalAnalysis.JsonEventlog.prototype.setEventlogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.TemporalAnalysis.EventLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TemporalAnalysis.EventLog}
 */
proto.TemporalAnalysis.JsonEventlog.prototype.addEventlogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.TemporalAnalysis.EventLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.TemporalAnalysis.JsonEventlog} returns this
 */
proto.TemporalAnalysis.JsonEventlog.prototype.clearEventlogsList = function() {
  return this.setEventlogsList([]);
};


