// source: processMining.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ProcessMining.EventLog');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ProcessMining.JsonEventLog');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProcessMining.EventLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProcessMining.EventLog.repeatedFields_, null);
};
goog.inherits(proto.ProcessMining.EventLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ProcessMining.EventLog.displayName = 'proto.ProcessMining.EventLog';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProcessMining.EventLog.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProcessMining.EventLog.prototype.toObject = function(opt_includeInstance) {
  return proto.ProcessMining.EventLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProcessMining.EventLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProcessMining.EventLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    processname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    eventlogList: jspb.Message.toObjectList(msg.getEventlogList(),
    proto.ProcessMining.JsonEventLog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ProcessMining.EventLog}
 */
proto.ProcessMining.EventLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ProcessMining.EventLog;
  return proto.ProcessMining.EventLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ProcessMining.EventLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ProcessMining.EventLog}
 */
proto.ProcessMining.EventLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProcessname(value);
      break;
    case 2:
      var value = new proto.ProcessMining.JsonEventLog;
      reader.readMessage(value,proto.ProcessMining.JsonEventLog.deserializeBinaryFromReader);
      msg.addEventlog(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ProcessMining.EventLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ProcessMining.EventLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ProcessMining.EventLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProcessMining.EventLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProcessname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEventlogList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ProcessMining.JsonEventLog.serializeBinaryToWriter
    );
  }
};


/**
 * optional string processName = 1;
 * @return {string}
 */
proto.ProcessMining.EventLog.prototype.getProcessname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessMining.EventLog} returns this
 */
proto.ProcessMining.EventLog.prototype.setProcessname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated JsonEventLog eventlog = 2;
 * @return {!Array<!proto.ProcessMining.JsonEventLog>}
 */
proto.ProcessMining.EventLog.prototype.getEventlogList = function() {
  return /** @type{!Array<!proto.ProcessMining.JsonEventLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ProcessMining.JsonEventLog, 2));
};


/**
 * @param {!Array<!proto.ProcessMining.JsonEventLog>} value
 * @return {!proto.ProcessMining.EventLog} returns this
*/
proto.ProcessMining.EventLog.prototype.setEventlogList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ProcessMining.JsonEventLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ProcessMining.JsonEventLog}
 */
proto.ProcessMining.EventLog.prototype.addEventlog = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ProcessMining.JsonEventLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ProcessMining.EventLog} returns this
 */
proto.ProcessMining.EventLog.prototype.clearEventlogList = function() {
  return this.setEventlogList([]);
};


