# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporalAnalysis.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16temporalAnalysis.proto\x12\x10TemporalAnalysis\"P\n\x0cJsonEventlog\x12\x11\n\tCompanyId\x18\x01 \x01(\x05\x12-\n\teventlogs\x18\x02 \x03(\x0b\x32\x1a.TemporalAnalysis.EventLog\"\x89\x01\n\x08\x45ventLog\x12\x13\n\x0bprocessName\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61seId\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x11\n\teventName\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\ndepartment\x18\x06 \x01(\t\x12\x10\n\x08\x63\x61seReff\x18\x07 \x01(\t\"A\n\x0bTaskHistory\x12\x32\n\x07history\x18\x01 \x03(\x0b\x32!.TemporalAnalysis.JsonTaskHistory\"\x9f\x01\n\x0fJsonTaskHistory\x12\x13\n\x0bprocessName\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61seId\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x11\n\teventName\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\ndepartment\x18\x06 \x01(\t\x12\x11\n\tCompanyId\x18\x07 \x01(\x05\x12\x0c\n\x04time\x18\x08 \x01(\x02\x32`\n\rTemporalMiner\x12O\n\x0eGetTaskHistory\x12\x1e.TemporalAnalysis.JsonEventlog\x1a\x1d.TemporalAnalysis.TaskHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temporalAnalysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONEVENTLOG']._serialized_start=44
  _globals['_JSONEVENTLOG']._serialized_end=124
  _globals['_EVENTLOG']._serialized_start=127
  _globals['_EVENTLOG']._serialized_end=264
  _globals['_TASKHISTORY']._serialized_start=266
  _globals['_TASKHISTORY']._serialized_end=331
  _globals['_JSONTASKHISTORY']._serialized_start=334
  _globals['_JSONTASKHISTORY']._serialized_end=493
  _globals['_TEMPORALMINER']._serialized_start=495
  _globals['_TEMPORALMINER']._serialized_end=591
# @@protoc_insertion_point(module_scope)
