import { Montserrat } from "next/font/google";
import "./globals.css";
// import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { ApolloWrapper } from "../lib/apollo-wrapper"
// import { ApolloWrapper } from "";
// import { useScrollToTop } from "@/components/hooks/useScrollToTop";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  // useScrollToTop();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
